# Site settings
title: Hamster Tracker
email: alex@bold-it.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/hamster" # the subpath of your site, e.g. /blog/
url: "http://jessica.themostaweso.me" # the base hostname & protocol for your site
twitter_username: boldbigflank
github_username:  boldbigflank

# Build settings
markdown: kramdown
